pull_request_rules:
  - name: Automatic merge during office hours
    description: Merge when PR passes all branch protection during office hours
    conditions:
      - schedule = Mon-Fri 00:01-23:59[Europe/Berlin]
    actions:
      merge:
  - name: Make sure PR are update before merging with rebase
    description: This automatically rebases PRs when they are out-of-date with the
      base branch to avoid semantic conflicts (next step us switch to merge
      queue).
    conditions:
      - "#commits-behind >= 10"
    actions:
      rebase:
  - name: Automatic merge
    description: Merge when PR passes all branch protection and has label automerge
    conditions:
      - label = automerge
    actions:
      merge:
