[settings]
experimental = true
color = true
yes = true
auto_install = true

[settings.python]
uv_venv_auto = "create|source"
uv_venv_create_args = ["--seed", "--system-site-packages"]

[settings.pipx]
uvx = true

[tools]
#node = { version = "24", postinstall = "corepack enable" }
node = "24"
bun = "latest"
python = "3.14"
uv = "latest"
ruff = "latest"
ty = "latest"
prek = "latest"
"pipx:pytest" = "latest"
"pipx:basedpyright" = "latest"

[env]
PROJECT_ROOT = "{{config_root}}"
UV_PYTHON = { value = "{{ tools.python.path }}", tools = true }
UV_LINK_MODE = "symlink"
_.python.venv = { path = ".venv", create = true, uv_create_args = ["--seed", "--system-site-packages"] }

[tasks.install]
description = 'Mise ci install'
file = '.mise/tasks/install'

[tasks.test]
description = "Run tests"
run = "pytest tests/"

[tasks.lint]
description = "Lint the code"
run = "ruff ."
